name: cts_tappable
description: A new Flutter package project.
version: 1.0.2
homepage: https://github.com/fsmcts/cts_tappable

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
